//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVC_Tbl_Emplyee
    {
        public int Id { get; set; }
        public string Emp_Name { get; set; }
        public Nullable<int> Emp_Age { get; set; }
        public string Emp_Gender { get; set; }
        public string Emp_MobileNo { get; set; }
    }
   
}
